# Generated by Django 4.0.4 on 2022-06-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('type_of_loginer', models.CharField(max_length=1000, null=True)),
                ('salt', models.CharField(default='False', max_length=1000)),
            ],
            options={
                'db_table': 'logins',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administrator_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Administrator.login')),
                ('administrator_name_of_organization', models.CharField(max_length=1000, null=True)),
                ('administrator_name_of_admin', models.CharField(max_length=1000, null=True)),
                ('administrator_mobileNumber', models.CharField(max_length=1000, null=True)),
                ('administrator_office_number', models.CharField(max_length=1000, null=True)),
                ('administrator_email', models.CharField(max_length=1000, null=True)),
                ('administrator_image', models.CharField(max_length=10000, null=True)),
                ('administrator_address', models.CharField(max_length=1000, null=True)),
                ('administrator_website', models.CharField(max_length=1000, null=True)),
                ('administrator_location_0f_organization', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('traveller_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Administrator.login')),
                ('traveller_name', models.CharField(max_length=1000, null=True)),
                ('traveller_gender', models.CharField(max_length=1000, null=True)),
                ('traveller_dob', models.CharField(default='1899-09-09', max_length=1000)),
                ('traveller_mobileNumber', models.CharField(max_length=1000, null=True)),
                ('traveller_email', models.CharField(max_length=1000, null=True)),
                ('traveller_image', models.CharField(max_length=10000, null=True)),
                ('traveller_address', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'traveller',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages_title_of_package', models.CharField(max_length=1000, null=True)),
                ('packages_description', models.CharField(max_length=1000, null=True)),
                ('packages_budget', models.CharField(max_length=1000, null=True)),
                ('packages_places_to_visit', models.CharField(max_length=1000, null=True)),
                ('packages_cities_we_stay', models.CharField(max_length=1000, null=True)),
                ('packages_pickup_point', models.CharField(max_length=1000, null=True)),
                ('packages_drop_point', models.CharField(max_length=1000, null=True)),
                ('packages_duration', models.CharField(max_length=1000, null=True)),
                ('packages_package_highlights', models.CharField(max_length=1000, null=True)),
                ('packages_no_of_bookings', models.CharField(max_length=1000, null=True)),
                ('packages_images1', models.CharField(max_length=10000, null=True)),
                ('packages_organisation_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Administrator.administrator')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookings_booking_quantity', models.CharField(default='1', max_length=100)),
                ('bookings_booking_status', models.CharField(default=False, max_length=100)),
                ('bookings_package_id', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Administrator.packages')),
                ('bookings_organisation_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Administrator.administrator')),
                ('bookings_traveller_id', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Administrator.traveller')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
